<?php
$salesmen = $this->salesmen;
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SALESMAN </title>
</head>
<body>
	<?php require 'view/html/header.phtml'; ?>
	<table class="table">
		<tr>
			<th>Manage Salesman</th>
			<th> <button> <a href="index.php?c=salesman&a=add">ADD</a> </button></th>
		</tr>
	</table>
	<table class="table table-success table-striped">
		<tr>
			<th>SALESMAN ID</th>
			<th>FIRST NAME</th>
			<th>LAST NAME</th>
			<th>EMAIL</th>
			<th>GENDER</th>
			<th>MOBILE</th>
			<th>STATUS</th>
			<th>CREATED AT</th>
			<th>UPDATED AT</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
	<?php foreach ($salesmen as $salesman): ?>
		<tr>
			<td><?php echo $salesman->salesman_id; ?></td>
			<td><?php echo $salesman->first_name; ?></td>
			<td><?php echo $salesman->last_name; ?></td>
			<td><?php echo $salesman->email; ?></td>
			<td><?php echo $salesman->gender; ?></td>
			<td><?php echo $salesman->mobile; ?></td>
			<td><?php echo $salesman->getStatusText($salesman->status); ?></td>
			<td><?php echo $salesman->created_at; ?></td>
			<td><?php echo $salesman->updated_at; ?></td>
			<td> <a href="index.php?c=salesman&a=edit&id=<?php echo $salesman->salesman_id; ?>">EDIT</a> </td>
			<td> <a href="index.php?c=salesman&a=delete&id=<?php echo $salesman->salesman_id; ?>">DELETE</a> </td>
		</tr>
	<?php endforeach; ?>
	</table>
</body>
</html>