<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>
<body>
    <?php require 'view/html/header.phtml'; ?>
    <table class="table">
        <tr>
            <th>category Add</th>
        </tr>
    </table>
        <form method="POST" action="index.php?c=category&a=save">
        <tr>
            <th> <button> <a href="index.php?c=customer&a=grid">CANCEL</a> </button></th>
            <th> <button type="submit"> SAVE </button></th>
        </tr>
            <table class="table table-success table-striped-columns">
                 <tr>
                    <td>Name</td>
                    <td><input type="text" name="category[name]"></td>
                </tr>
                 <tr>
                    <td>description</td>
                    <td><input type="text" name="category[description]"></td>
                </tr>
                <?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
           <tr>
              <td>Status</td>
              <td>
                 <select name="category[status]">
                        <?php foreach ($statusOptions as $value => $label):?>
                        <option value="<?php echo $value;?>"><?php echo $label;?></option>
                        <?php endforeach; ?>
                    </select>
              </td>
           </tr>
            </table>
        </form>
    </table>
</body>
</html>