<?php
$category = $this->getData();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Edit</title>
</head>
<body>
	<?php require 'view/html/header.phtml'; ?>
	<table class="table table-success table-striped-columns">
		<tr>
			<th>Category Edit</th>
		</tr>
	</table>
	<tr>
		<th> <button> <a href="index.php?c=category&a=grid">CANCEL</a> </button></th>
		<th> <button type="submit"> SAVE </button></th>
	</tr>
	<form method="POST" action="index.php?c=category&a=save&id=<?php echo $category->category_id?>">
			<table class="table table-success table-striped-columns">
				<tr>
					<td>Name</td>
					<td><input type="text" name="category[name]" value="<?php echo $category->name;?>">
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td><input type="text" name="category[description]" value="<?php echo $category->description;?>">
					</td>
				</tr>
				<?php $statusOptions = [1=>"Active" , 2=>"Inactive"];?>
			    <tr>
			      <td>Status</td>
			      <td>
			         <select name="category[status]">
			         <?php foreach ($statusOptions as $value => $label):?>
			         <option value="<?php echo $value;?>" <?php if ($category->status==$value)echo "selected";?>><?php echo $label;?></option>
			         <?php endforeach; ?>
			         </select>
			      </td>
			   </tr>
			</table>
		</form>
	</table>
</body>
</html>