<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>ADD</title>
</head>
<body>

	<table border="1px">
		<tr>
			<th>Product With Adapter</th>
		</tr>
	</table>
	<form action="index.php?c=Product&a=insert" method="POST">
		<table border="1px">
			<tr>
				<td>PRODUCT NAME</td>
				<td> <input type="text" name="Product[name]"> </td>
			</tr>
			<tr>
				<td>COST</td>
				<td> <input type="text" name="Product[cost]"> </td>
			</tr>
			<tr>
				<td>PRICE</td>
				<td> <input type="text" name="Product[price]"> </td>
			</tr>
			<tr>
				<td>SKU</td>
				<td> <input type="text" name="Product[sku]"> </td>
			</tr>
			<tr>
				<td>STATUS</td>
				<td>
					<select name="Product[status]">
						<option>SELECT</option>
						<option>ACTIVE</option>
						<option>INACTIVE</option>
					</select>

				</td>
			</tr>
		
			<tr>
				<td>COLOR</td>
				<td> <input type="text" name="Product[color]"> </td>
			</tr>
			<tr>
				<td>MATERIAL</td>
				<td> <input type="text" name="Product[material]"> </td>
			</tr>
			<tr>
				<th> <button> <a href="index.php?c=Product&a=grid">CANCEL</a> </button></th>
				<th> <button type="submit"> SAVE </button></th>
			</tr>
		</table>
	</form>

</body>
</html>