<?php
$customers = $this->customers
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Customer </title>
</head>
<body>
	<?php require 'view/html/header.phtml'; ?>
	<table class="table">
		<tr>
			<th>Manage Customer</th>
			<th> <button> <a href="index.php?c=customer&a=add">ADD</a> </button></th>
		</tr>
	</table>
	<table class="table table-success table-striped">
		<tr>
			<th>CUSTOMER ID</th>
			<th>FIRST NAME</th>
			<th>LAST NAME</th>
			<th>EMAIL</th>
			<th>GENDER</th>
			<th>MOBILE</th>
			<th>STATUS</th>
			<th>CREATED AT</th>
			<th>UPDATED AT</th>
			<th>EDIT</th>
			<th>DELETE</th>
		</tr>
	<?php foreach ($customers as $customer): ?>
		<tr>
			<td><?php echo $customer->customer_id; ?></td>
			<td><?php echo $customer->first_name; ?></td>
			<td><?php echo $customer->last_name; ?></td>
			<td><?php echo $customer->email; ?></td>
			<td><?php echo $customer->gender; ?></td>
			<td><?php echo $customer->mobile; ?></td>
			<td><?php echo $customer->getStatusText($customer->status); ?></td>
			<td><?php echo $customer->created_at; ?></td>
			<td><?php echo $customer->updated_at; ?></td>
			<td> <a href="index.php?c=customer&a=edit&id=<?php echo $customer->customer_id; ?>">EDIT</a> </td>
			<td> <a href="index.php?c=customer&a=delete&id=<?php echo $customer->customer_id; ?>">DELETE</a> </td>
		</tr>
	<?php endforeach; ?>
	</table>
</body>
</html>