<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>ADD</title>
</head>
<body>

	<?php require 'view/html/header.phtml'; ?>
	<table class="table table-striped">
		<tr>
			<th>Product Add</th>
		</tr>
	</table>
	<form action="index.php?c=product&a=insert" method="POST">
		<table class="table table-striped">
			<tr>
				<td>PRODUCT NAME</td>
				<td> <input type="text" name="name"> </td>
			</tr>
			<tr>
				<td>COST</td>
				<td> <input type="text" name="cost"> </td>
			</tr>
			<tr>
				<td>SKU</td>
				<td> <input type="text" name="SKU"> </td>
			</tr>
			<tr>
				<td>PRICE</td>
				<td> <input type="text" name="price"> </td>
			</tr>
			<tr>
				<td>Quantity</td>
				<td> <input type="text" name="quantity"> </td>
			</tr>
			<tr>
				<td>DISCRIPTION</td>
				<td> <input type="text" name="description"> </td>
			</tr>
			<tr>
				<td>STATUS</td>
				<td>
					<select name="status">
						<option value="">SELECT STATUS</option>
						<option>ACTIVE</option>
						<option>INACTIVE</option>
					</select>

				</td>
			</tr>
		
			<tr>
				<td>COLOR</td>
				<td> <input type="text" name="color"> </td>
			</tr>
			<tr>
				<td>MATERIAL</td>
				<td> <input type="text" name="material"> </td>
			</tr>
			<tr>
				<th> <button> <a href="index.php?c=product&a=grid">CANCEL</a> </button></th>
				<th> <button type="submit"> SAVE </button></th>
			</tr>
		</table>
	</form>

</body>
</html>