<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>ADD</title>
</head>
<body>

	<?php require 'view/html/header.phtml'; ?>
	<table class="table table-striped">
		<tr>
			<th>Product Edit</th>
		</tr>
	</table>
	<form action="index.php?c=product&a=update&id=<?php echo $product['product_id']; ?>" method="POST">
		<table class="table table-striped">
			<tr>
				<td>PRODUCT NAME</td>
				<td> <input type="text" name="name" value="<?php echo $product['name'] ?>">  </td>
			</tr>
			<tr>
				<td>COST</td>
				<td> <input type="text" name="cost" value="<?php echo $product['cost'] ?>">  </td>
			</tr>
			<tr>
				<td>PRICE</td>
				<td> <input type="text" name="price" value="<?php echo $product['price'] ?>">  </td>
			</tr>
			<tr>
				<td>SKU</td>
				<td> <input type="text" name="sku" value="<?php echo $product['sku'] ?>">  </td>
			</tr>
			<tr>
				<td>STATUS</td>
				<td>
					<select name="status" value="<?php echo $product['status'] ?>"> 
						<option>SELECT STATUS</option>
						<option>ACTIVE</option>
						<option>INACTIVE</option>
					</select>

				</td>
			</tr>
			
			<tr>
				<td>DISCRIPTION</td>
				<td> <input type="text" name="description" value="<?php echo $product['description'] ?>">  </td>
			</tr>
			<tr>
				<td>COLOR</td>
				<td> <input type="text" name="color" value="<?php echo $product['color'] ?>">  </td>
			</tr>
			<tr>
				<td>MATERIAL</td>
				<td> <input type="text" name="material" value="<?php echo $product['material'] ?>">  </td>
			</tr>
			<tr>
				<th> <button> <a href="index.php?c=product&a=grid">CANCEL</a> </button></th>
				<th> <button type="submit"> SAVE </button></th>
			</tr>
		</table>
	</form>

</body>
</html>